# Generated by Django 5.2.10 on 2026-01-18 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pizzas", "0002_rename_entry_topping"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topping",
            old_name="text",
            new_name="name",
        ),
    ]
