# Generated by Django 5.2.10 on 2026-01-18 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pizzas", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Entry",
            new_name="Topping",
        ),
    ]
